# Introduction

## Overview
Mixed model 은 데이터 안 관측값들 사이에 dependency 가 있는 경우에 사용할 수 있는 매우 유용한 모델링 방법이다. 이 상황에서는 일반적으로 군집을 이루고 있는 관측값들로 부터 상관성이 생긴다. 예를 들어, 데이터가, 관측값 단위들로 반복 측정을 한 데이터가 있거나, 단위 관측값들이 서로 그룹을 이루는 경우가 자주 일어난다. (예, 학교에 속한 학생들, 한 지역의 여러 도시들). 이러한 상황을 다루는 법은 여러 방법이 있지만, mixed model 은 매우 일반적이고 강력한 방법이다. 또한, 응용성이 확장되는 다른 통계적 방법들과 밀접한 관계를 이룬다.  

### Goals

This document also serves as the basis for a workshop. The goal of the workshop is primarily to provide a sense of when one would use mixed models and a variety of standard techniques to implement them.  Exercises are available to practice your skills.


### 준비하기

The document is for the most part very applied in nature, and only assumes a basic understanding of standard regression models. Use of R for regression modeling is also assumed, though there will be some review.  Demonstrations will be done almost entirely with the <span class="pack">lme4</span> package.

Note the following color coding used in this document:

- <span class="emph">emphasis</span>
- <span class="pack">package</span>
- <span class="func">function</span>
- <span class="objclass">object/class</span>
- [link]() (with hover underline)


## Workshop

If doing or interested in the workshop follow these steps:

0. Download the zip file at [GitHub](https://github.com/m-clark/mixed-models-with-r-workshop-2019/archive/master.zip). Be mindful of where you put it.
1. Unzip it. Be mindful of where you put the resulting folder.
2. Open RStudio.
3. File/Open Project and click on the blue icon (`mixed-models-with-r-workshop-2019.Rproj`) in the folder you just created.
4. File/Open Click on the ReadMe file and do what it says.


## Key packages

To run the code in this document you'll really only need the following:

- <span class="pack">lme4</span> 
- <span class="pack">tidyverse</span> (for data processing)
- <span class="pack">merTools</span> (optional)
- <span class="pack">glmmTMB</span> (optional)
- <span class="pack">brms</span> (optional)
- <span class="pack">modelr</span> (optional)
- <span class="pack">nlme</span> (part of base R, no need for install)

I also use a custom package called <span class="pack">mixedup</span> that provides more usable and printable output for mixed models from <span class="pack">lme4</span>, <span class="pack">brms</span>, <span class="pack">mgcv</span>, etc. Much of the output you see will come from that.